### ISSUE TITLE
Not working when there's manual commands

### ISSUE THREAD

**Issue by iurijacob** [bizley/yii2-migration#10]
Hi,

I'm having a lot of problems when calling migration/update because of some commands that I've ran on old migrations. For example:

```PHP
Yii::$app->db->createCommand("UPDATE some_table SET child_id = id")->execute();
```
I cannot just throw those commands away, unfortunately.

Is there some workaround to make your migration/update work in that case? One good solution would be using a kind of 'ignore' annotation that tells de parser to ignore the line just below it. Like this:

```PHP
/* @ignore */
Yii::$app->db->createCommand("UPDATE some_table SET child_id = id")->execute();
```

This would be enough. By now I'm commenting and uncommenting those lines to make it work .

By the way, good job with this extension. Very helpful indeed.

**Comment by bizley** [comment]
Yes, there is solution (mentioned in the readme) - use `skipMigrations` in the configuration for the component but this will ignore whole migration file, not just a single line.

**Comment by iurijacob** [comment]
Yes, I know. But I've tried that and it didn't work for me. Some of my migrations are just too big to be ignored. I'll try to implement the annotation solution ASAP in a separated fork so you can bring it to your master if you like. 
Thanks.
