### ISSUE TITLE
[BUG] v4.0.3 First update file does not have a prefix

### ISSUE THREAD

**Issue by tsvetiligo** [bizley/yii2-migration#101]
Yii v2.0.35
Yii 2 Migration Generator Tool v4.0.3
MySQL 5.7

If the update generates more than one file, the first file does not have a prefix (“01”), but all subsequent ones have (“02” and so on).

**Comment by bizley** [comment]
Fixed in [4.0.4](https://github.com/bizley/yii2-migration/releases/tag/4.0.4)
