### ISSUE TITLE
[Bug] new version do not create migrations

### ISSUE THREAD

**Issue by tonykor** [bizley/yii2-migration#115]
**Describe the bug**
The script not make any migration saying that all the tables in the exclude list, but i have not an exclude list, neither know for to list/add items to the exclude list. Creating migration for tables one by one is ok and worked as expected

```
php yii migration/create * --generalSchema=0
Yii 2 Migration Generator Tool v4.1.1

 > No matching tables in the database.
 > 1 table excluded by the config.
```

**Affected versions**
mysql 8.0.17

**Comment by bizley** [comment]
Are you using docker here? Does it work if you run `php yii migration/create "*" --generalSchema=0`?
