### ISSUE TITLE
[Bug] update after renameTable()

### ISSUE THREAD

**Issue by tsvetiligo** [bizley/yii2-migration#119]
Yii v2.0.38
Yii 2 Migration Generator Tool v4.1.1
MySQL 5.7

Create migration with renameTable() and run update:
- if changing the field in the table through the DB - the utility creates a migration with the createTable() instead of updating the field
- if changing a field in the table through migration, the utility creates a migration with addColumn() for all fields instead of nothing

**Comment by bizley** [comment]
Could you provide me with migration example and exact steps for reproducing? Thanks.
