### ISSUE TITLE
[Bug] update of a migration does not work without Yii autoloader

### ISSUE THREAD

**Issue by My6UoT9** [bizley/yii2-migration#127]
**Describe the bug**
When trying to update an existing migration, this happens:
```
Yii 2 Migration Generator Tool v4.1.2
 > 1 table excluded by the config.

 > Comparing current table 'region' with its migrations ...ERROR!
 > Setting unknown property: m200508_094946_0163_create_table_session_backend::experimental

```
**Expected behavior**
Successfull update

**Additional context**
The error happens in Extractor.php Line 66, where it tries to initialize the existing migration, with the params db, and experimental. But the Migration Class does not know about experimental.
Possibly this worked in a earlier yii version.

**Affected versions**
yii 2.0.40

**Comment by My6UoT9** [comment]
I believe this is related to this piece of code:
```
     */
    private function setDummyMigrationClass(): void
    {
        Yii::$classMap['yii\db\Migration'] = Yii::getAlias('@bizley/migration/dummy/Migration.php');
    }
```
As I do not use the yii autoloader. Lets see how todo that with composer.

**Comment by bizley** [comment]
Hmm, this might be tricky without Yii autoloader. I definitely need to replace the original class with mine. I'll try to find the answer, if you have any please let me know.

**Comment by bizley** [comment]
@My6UoT9 could you check if provided PR fixes it in your case? What I'm doing here is forcing the registration of Yii autoloader inside the extractor. AFAIK double registration of the same function is skipped so it should be safe.

**Comment by My6UoT9** [comment]
> @My6UoT9 could you check if provided PR fixes it in your case? What I'm doing here is forcing the registration of Yii autoloader inside the extractor. AFAIK double registration of the same function is skipped so it should be safe.

Yes it works, it also works when the autoloader from yii was already registred.
Thanks for fixing!
