### ISSUE TITLE
[Bug]  > SQLSTATE[08004] [1040] Too many connections

### ISSUE THREAD

**Issue by My6UoT9** [bizley/yii2-migration#128]
**Describe the bug**
Trying to update a list of tables, causes too many connections.

**Expected behavior**
It should not open to many sql connections.

**Additional context**
In Extractor.php, if I remove clone - it works as expected.
`$this->subject = new $migration(['db' => clone $this->db, 'experimental' => $this->experimental]);`

(I solved it for myself, by just running each update separately.. )

**Affected versions**
4.1.2

**Comment by bizley** [comment]
Hmm, yes, looks like I must to clone it earlier. Cheers.
