### ISSUE TITLE
[Bug] Asterisk not working with migration/create

### ISSUE THREAD

**Issue by echantigny** [bizley/yii2-migration#131]
**Describe the bug**
If I run the listing command, I see all my tables.
```
> php yii migration
Yii 2 Migration Generator Tool v4.1.2
 > Your database contains 147 tables:
[...LIST OF TABLES ...]
```

If I run create with *, it doesn't do anything
```
> php yii migration/create *
Yii 2 Migration Generator Tool v4.1.2
 > No matching tables in database.
```

If I run it with a specific table, it works as expected.
```
> php yii migration/create company
Yii 2 Migration Generator Tool v4.1.2
 > Generating migration for creating table 'company' ...DONE!
 > Saved as '/srv/migrations/m210324_153303_create_table_company.php'
```

**Expected behavior**
A migration containing all the tables listed.

**Affected versions**
What version of `yii2-migration` are you working with? (Please remember that v1, v2, and v3 are not supported anymore)
What is the database engine and its version?

I'm using 4.1.2 (just installed with Composer today) and my database is mySQL (mariaDB).

**Comment by bizley** [comment]
Have you tried with `yii migration/create "*"` like described in readme?

**Comment by echantigny** [comment]
Sorry, I haven't.  I was following the instructions here, so that might be required an update?
https://www.yiiframework.com/extension/yii2-migration-creator

**Comment by echantigny** [comment]
Oh and yes, that does work.

**Comment by echantigny** [comment]
And never mind, just saw the fine prints under

> In environments that hijack asterisk (like dockerized env) use "*".

**Comment by bizley** [comment]
Great ;) Cheers.
