### ISSUE TITLE
[Q] Unable to get Migration Working Correctly

### ISSUE THREAD

**Issue by hkbertoson** [bizley/yii2-migration#146]
Hello! I have run ````migration/create tbl_"*"```` and it creates all the migrations just fine. But then i go and run ````yii migrate```` it tells me that no new migrations are found and my system is up to date. Am I doing something wrong?

**Comment by bizley** [comment]
It's hard to tell without more details.
1. Can you confirm that newly created migrations are stored in a proper place?
2. Are you using `fixHistory` option to add new migrations to the list of applied migrations?
3. Is the `migrate` controller checking for new migrations in the same place where `migration` is saving them?

**Comment by hkbertoson** [comment]
I found the issue. Thanks! I had to change 
`  'migrationPath' => '@common/migrations/db',` to `  'migrationPath' => '@console/migrations',`
