### ISSUE TITLE
migration/update produces: Column data must be provided as an instance of yii\db\ColumnSchemaBuilder

### ISSUE THREAD

**Issue by optmsp** [bizley/yii2-migration#156]
**Describe the bug**
When running migration/update for all tables, it fails pretty quickly with:

`Column data must be provided as an instance of yii\db\ColumnSchemaBuilder. Do you have column configuration provided as a string while not using experimental mode (--ex)?_`

**Expected behavior**
migration/update should parse out all correct migrations.

**Affected versions**
i just pulled dev-master as of nov 7 2021

**Additional context**
I know what is causing it at least. I dug into the existing issues for this library and found:
https://github.com/bizley/yii2-migration/issues/132

This is the exact error I'm getting. Knowing that, I tested that this is the same issue by finding any migrations that have an ENUM. I found one and set migrations/update to skip it. migrations/update is now able to move forward.

That said, I'd rather NOT exclude the migration because, Murphy's Law, I will instantly need to update that migration in all upcoming releases because that's how bad luck works. :)

Here is the relevant section of the migration that I had to exclude because of the ENUM:

```
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%schedule_option}}',
            [
                'id' => $this->primaryKey(),
                'uuid' => $this->string(36),
                'oplock' => $this->integer()->defaultValue('0')->notNull(),
                'created_at' => $this->dateTime()->notNull()->defaultExpression('CURRENT_TIMESTAMP'),
                'created_by' => $this->integer(),
                'deleted_at' => $this->dateTime(),
                'deleted_by' => $this->integer()->defaultValue('0'),
                'updated_at' => $this->dateTime(),
                'updated_by' => $this->integer(),
                'sort_order' => $this->integer()->notNull(),
                'name' => $this->string()->notNull(),
                'schedule_type_id' => $this->integer()->notNull(),
                'day_of_week' => $this->integer(),
                'day_of_month' => $this->integer(),
                'recurring' => "ENUM('Every Day', 'Every Week Day')",
            ],
            $tableOptions
        );
...
```

I wondered why I had done this using a string instead of the normal yii2 $this->DB_TYPE(), and found that yii2 migrations apparently don't support enums directly, and instead recommend that it is created using the method above.

Would love ideas on how to solve this so that I do not need to "skip" this important migration (or future ones where I am using an ENUM column type).

**Comment by bizley** [comment]
Yes, it's true that Yii does not support enum with provided methods but the solution here is provided in the error message - please use experimental mode that should take care of it.
