### ISSUE TITLE
[Bug] Setting default values using expressions fails

### ISSUE THREAD

**Issue by khalid-eyez** [bizley/yii2-migration#177]
**Describe the bug**
setting default values using expressions fails in version 4.3.1 because expressions are resolved to something that is not accepted in MySQL, I am using 10.4.24-MariaDB.

**Affected versions**
v4.3.1

database engine:
Innodb (10.4.24-MariaDB)

![dcc](https://user-images.githubusercontent.com/58696642/187837510-5c3dcf45-ace2-44f3-b801-85701872bc66.PNG)
![bug1](https://user-images.githubusercontent.com/58696642/187837524-a2e622fd-3333-4b8d-9561-7768832fe462.PNG)

**Comment by bizley** [comment]
> version 4.3.1 of this extension has already been released but i cannot get it through composer

How do you have it set in the composer.json?

And as for the rest:
Please provide me with the SQL statement to create the table you made the migration of.

**Comment by khalid-eyez** [comment]
okay i have verified the version is 4.3.1 even if in the file migrationController it is still 4.3.0

**Comment by khalid-eyez** [comment]
that is how it was created...you can see how different it is from the output of the migration command

**Comment by bizley** [comment]
This is happening because of [this line](https://github.com/yiisoft/yii2/blob/2.0.46/framework/db/mysql/Schema.php#L296) in Yii 2 core. The expression `current_timestamp()` or `current_timestamp` is recognized only for columns of type `datetime` or `timestamp` while you are providing `date` and `time` here. But since it works obviously (on MariaDB at least, MySQL is not allowing functions as defaults) I need to see if the update in the Yii 2 needs to be done.

**Comment by bizley** [comment]
If the update happens I will link it here but since this depends on the Yii core I cannot fix it and it won't work for previous versions of Yii anyway.

**Comment by khalid-eyez** [comment]
> This is happening because of [this line](https://github.com/yiisoft/yii2/blob/2.0.46/framework/db/mysql/Schema.php#L296) in Yii 2 core. The expression `current_timestamp()` or `current_timestamp` is recognized only for columns of type `datetime` or `timestamp` while you are providing `date` and `time` here. But since it works obviously (on MariaDB at least, MySQL is not allowing functions as defaults) I need to see if the update in the Yii 2 needs to be done.

but YII2 have added another function which i thought would work properly in this case, defaultExpression(). since expressions like current_timestamp or current_timestamp() work well in a database for date columns, i think it should be handled well to work with migrations for the same column types.

**Comment by bizley** [comment]
The method you are talking about is used to create an sql statement but here I'm extracting this data from the table and Yii is not aware that it is an expression because of what I showed you so it says it must be a simple text.

**Comment by khalid-eyez** [comment]
Okay that's a YII2 fix then

**Comment by bizley** [comment]
My fix is already merged, waiting for the release.

**Comment by bizley** [comment]
[Yii 2.0.47](https://github.com/yiisoft/yii2/blob/2.0.47/framework/CHANGELOG.md) has been released.
