### ISSUE TITLE
[Bug] Invalid path alias: @bizley/migration/views/migration.php

### ISSUE THREAD

**Issue by Choate** [bizley/yii2-migration#179]
**Describe the bug**
run `./yii.php migration/create test`

`Invalid path alias: @bizley/migration/views/migration.php`

**Expected behavior**
set default alias `@bizley` path

**Additional context**
config.php

```php
'controllerMap' => [
    'migration' => [
        'class' => 'bizley\migration\controllers\MigrationController',
    ],
],
```

**Affected versions**
Version: v4
MySQL: 5.7

**Comment by bizley** [comment]
How did you install it? The alias should be created automatically during the composer installation.

**Comment by Choate** [comment]
> How did you install it? The alias should be created automatically during the composer installation.

`composer require bizley/migration -vvv`

but no alias path is created automatically

It is recommended to configure the alias path as one of the properties of MigrationController

**Comment by bizley** [comment]
I've just did the clean installation with advanced app template and it works like expected. Please provide me with the exact steps to recreate this on Linux environment.

Also check `vendor/yiisoft/extensions.php` - there should be entry like this:

**Comment by Choate** [comment]
thanks, i found the problem, i didn't set the `basePath` correctly, so the `extension.php` file could not be imported correctly
