### ISSUE TITLE
[Bug] Multiple definitions exist for class 'Migration' 

### ISSUE THREAD

**Issue by NickGoodwind** [bizley/yii2-migration#184]
### **Bug**
Currently both classes `MigrationSql` and `MigrationChanges` located in `bizley/migration/src/dummy` are using the same namespace as the default base `Migration` class from Yii, which overlaps definitions and overwrites the default class that can no longer be used with other extensions.

### **Expected behavior**
That both classes have a separate distinct namespace for each of them that can be differentiated from the original Yii namespace. Furthermore, the namespace to be used should describe the package is coming from such as `bizley\db\migration` so it does not affect other extensions.

### **Affected versions**
Yii 2 Migration Generator Tool v4.4.1

### **What is the database engine and its version?**
InnoDB

**Comment by bizley** [comment]
This is done on purpose to allow class autoloader to override the code. This process should only happen when the package is running anyway, how does it affect your application?

**Comment by NickGoodwind** [comment]
Bizley it affects the app because I have installed a second external package `insolita/yii2-migration-generator` and it creates an error while trying to create a new data migration "Fatal error: calling getSchema() on a string" 

So for example, if I have made a Model structural change that implied new data in DB I have to uninstall the package to be able run the data migration tool to persist curret DB state and then install back the package to be able to use the update option to have the current table structure persisted as an update migration.

But I understand your idea to override the code and if no other package is being used it makes perfect sense. Thank you for the really fast response on the issue.

**Comment by NickGoodwind** [comment]
No problem, I really appreciate your response and it really is not neccesary to go over this. The "BUG" is not as important as I don't really use both tools at the same time that much and the process to activate and deactivate is not time or effort comsuming.
