### ISSUE TITLE
PHP Fatal error:

### ISSUE THREAD

**Issue by kavasey** [bizley/yii2-migration#26]
Hi,

Thank you for great extension. But it gives me error...find below, would appreciate any workarounds, thanks

`Generating create migration for table 'actions' ...PHP Fatal error:  Cannot use yii\base\Object as Object because 'Object' is a special class name i
n C:\xampp\htdocs\bialab\vendor\bizley\migration\table\TableStructure.php on line 6
`

**Comment by bizley** [comment]
You are using PHP 7.2 and this package still supports older version where `Object` is used. As I said I'm going to release new version in #22 that will fix this. Since it's requested more and more I'll do it during the weekend so stay tuned.

**Comment by kavasey** [comment]
@bizley Thanks for the prompt response. On standby.

**Comment by bizley** [comment]
[Version 3.0.0](https://github.com/bizley/yii2-migration/releases/tag/3.0.0) has been released. Let me know if something is wrong ;)

**Comment by bizley** [comment]
It's this the case of using `generalSchema` parameter? Check the docs.
