### ISSUE TITLE
Size for char fields is not respected

### ISSUE THREAD

**Issue by gvlasov** [bizley/yii2-migration#29]
When I e.g. have a field with type `char(32)`, in the migration generated the code for that field is just `$this->addColumn(...)->char()`, with no size specified, which results in size 1 field to be created on migration application.

**Comment by bizley** [comment]
What is the value of `generalSchema` parameter in your case?

**Comment by gvlasov** [comment]
@bizley I don't change it in command line parameters or configuration options, so it must be the default value, 1. I didn't know about that parameter, I set it to 0 and I got what I needed, thanks.
