### ISSUE TITLE
Multiple DBs

### ISSUE THREAD

**Issue by sdlins** [bizley/yii2-migration#35]
Hi, I am trying to use your extension but, when I run `migrategen` or `migrategen/list` it throws an error because I don't have a `db` config since I have many (db_a, db_b,... db_x). 
If I try to specify `--db=db_x` I see: `Error: Unknown option: --db`.

So, how can I specify the `db` config I want to use when listing, creating, etc?

Thank you.

--edit
I know I can specify that in the configs for your extension, but, is there anyway to specify for each command? Otherwise it would be unusable to me (or to anyone having multiple dbs). Thank you again.

**Comment by bizley** [comment]
My bad - I forgot to include `db` option for `list` command. All other commands allow to set it from command line. I will fix this tonight (or if you want to create PR feel free, it's Hacktoberfest :smile:  )

**Comment by bizley** [comment]
Fixed in [3.0.3](https://github.com/bizley/yii2-migration/releases/tag/3.0.3)/[2.3.3](https://github.com/bizley/yii2-migration/releases/tag/2.3.3)

**Comment by sdlins** [comment]
Thank you @bizley. Yeah, I really realized that it wass the only option lacking. :+1:
