### ISSUE TITLE
Change MySQL table options in config

### ISSUE THREAD

**Issue by lostsnow** [bizley/yii2-migration#39]
MySQL table options is hardcoded with `CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB`

**Comment by bizley** [comment]
Right. Worth to make it configurable.

**Comment by bizley** [comment]
Fixed in [3.0.4](https://github.com/bizley/yii2-migration/releases/tag/3.0.4) / [2.3.4](https://github.com/bizley/yii2-migration/releases/tag/2.3.4) version.
