### ISSUE TITLE
Issue with version 3.0.4 

### ISSUE THREAD

**Issue by GnychP** [bizley/yii2-migration#40]
When default value in table is number, php returns an error.

`Argument 1 passed to bizley\migration\table\TableColumn::escapeQuotes() must be of the type string, integer given, called in \vendor\bizley\migration\src\table\TableColumn.php on line 126`

For me, the solution was to convert value ​​from int to string in this line of code. :)

**Comment by bizley** [comment]
Fixed in [3.0.5](https://github.com/bizley/yii2-migration/releases/tag/3.0.5).
