### ISSUE TITLE
Not working with switch statement in db.config

### ISSUE THREAD

**Issue by Scanerrr** [bizley/yii2-migration#42]
After run `php yii migration/list`
I get an **error**

```
Yii 2 Migration Generator Tool v3.0.5

Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known. '

in ...path\vendor\yiisoft\yii2\db\Connection.php:624
```

My **DbConfig** have a switch statement in there
```PHP 
<?php
// DB CONFIG
switch ($_SERVER['HTTP_HOST']):
    case 'test.loc':
        return [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname=partner',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8'
        ];
        break;
    default:
        return [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=host;dbname=dbnamehost',
            'username' => 'username',
            'password' => 'pass',
            'charset' => 'utf8'
        ];
        break;
endswitch;
```

**So after removing a swtich statement, everything works fine, but it's not an solution**

**Comment by bizley** [comment]
This has nothing to do with my package. What you can do is:

- Check if `$_SERVER` variable is available in you CLI environment and if `$_SERVER['HTTP_HOST']` is set at all.
- Verify if the host name you are providing if resolvable at all, your error suggests it's not.

**Comment by Scanerrr** [comment]
You're definitly right
`$_SERVER['HTTP_HOST']` is returning  `NULL`

Sorry for bothering!
You helped a lot!
