### ISSUE TITLE
Unsigned integer as 10 chars length

### ISSUE THREAD

**Issue by TomaszKane** [bizley/yii2-migration#43]
Hi, just tiny case...
is it possible to generate unsigned integer field with 10 chars length? In example, this:
`'updated_at' => $this->integer(10)->unsigned()->notNull(),`
instead of this:
`'updated_at' => $this->integer()->unsigned()->notNull(),`

Because unsigned int's take 10 chars, not 11 (default).

**Comment by bizley** [comment]
Yes, it should work with `generalSchema` parameter set to `0` (default is `1`).

**Comment by bizley** [comment]
Sure thing. `utf8mb4` is there by default but you can change it by setting `tableOptionsInit` parameter. Default is [here](https://github.com/bizley/yii2-migration/blob/master/src/controllers/MigrationController.php#L129-L132).

I'm almost sure that Yii is not storing collation info of a DB table so there is no way of detecting it and applying automatically without some additional DB specific queries so you need to configure it as described.

**Comment by TomaszKane** [comment]
Yup, I already do this. Thanks.
