### ISSUE TITLE
Strings length 

### ISSUE THREAD

**Issue by sahifedp** [bizley/yii2-migration#46]
Hi 
before anything thanks for this good and clear extension.

I have problem with `char` and `varchar` types that has length in DB.
after generate , in migration class , strings  not has length.

my field: 
        `title varchar(45) DEFAULT NULL,`

generated: 
        `'title' => $this->string(),`

must generated: 
       `'title' => $this->string(45),`

MY DB:  MySql version 5.7.24
Yii Version : 2.0.15.1
PHP version: 7.1

Thanks

**Comment by bizley** [comment]
It's because `generalSchema` parameter is set by default to 1 (as mentioned in readme) and with this schema generated is always left with default Yii values for specific column type. You can change it by setting `generalSchema` (or alias `g`) to `0`.

Thanks!
