### ISSUE TITLE
--migration Lookup option

### ISSUE THREAD

**Issue by artmarkov** [bizley/yii2-migration#53]
The standard command with the --migration Lookup option does not work. Command yii migrate --migrationLookup=@ ... ends with error: Error: Unknown option: --migrationLookup. We have to temporarily disable Your module.

**Comment by bizley** [comment]
I don't know what you are talking about. What should this --migration Lookup option do? And what kind of a standard is that? Does Yii respect this somehow somewhere?

**Comment by bizley** [comment]
I'm closing it since there is no answer. If you want to reopen it feel free to write a comment here.
