### ISSUE TITLE
Generating alter column when not needed and autocomplete primary issue

### ISSUE THREAD

**Issue by andrewpros** [bizley/yii2-migration#57]
Hi.

Looks like migration update with -g=0 generates the same columns alter code over and over with tinyInteger or smallInteger.

Also, still with -g=0 parameter, it generates double autoincremet primary key string when the first time migration generate was in g=1 mode, string like this

$this->integer(11)->notNull()->append('AUTO_INCREMENT PRIMARY KEY AUTO_INCREMENT PRIMARY KEY')

**Comment by bizley** [comment]
Could you paste here SQL for the table that makes this problem? Initial SQL and SQL for update. And please state the DB engine you are using.

Do I understand it correctly? - generating that migration with -g=0 and then generating update migration without any change creates the migration with alters?

**Comment by andrewpros** [comment]
Yeah, generating migration update with the same set of parameters generates alters but with exactly the same migration code for tinyInteger or smallInteger that is already there.
I will provide more details later.

**Comment by bizley** [comment]
Fixed in [3.6.2](https://github.com/bizley/yii2-migration/releases/tag/3.6.2) / [2.9.2](https://github.com/bizley/yii2-migration/releases/tag/2.9.2).

Thanks!

**Comment by andrewpros** [comment]
Ahh, totally forgot about this, i was on tight schedule so i just corrected it manually, sorry, but nevertheless thx for fix.
