### ISSUE TITLE
Size for columns is not respected

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-migration#58]
Similar to #29 
Version: 3.5.0

Table schema:
```
`updated_by` int(10) unsigned DEFAULT NULL,
`subject` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
```
Generated migration is:
```
'updated_by' => $this->integer()->unsigned(),
'subject' => $this->string()->notNull(),
```
should be:
```
'updated_by' => $this->integer(10)->unsigned(),
'subject' => $this->string(128)->notNull(),
```

Yii2 provide this data in:
`Yii::$app->db->getSchema()->tableSchemas[15]->getColumn('created_at')->size`

Can you support this?

**Comment by bizley** [comment]
I need to ask the same question as in linked issue - does changing `generalSchema` helps in your case?

**Comment by tomaszkane** [comment]
generalSchema On (default)
```
'file_id' => $this->primaryKey()->unsigned(),
'name' => $this->string()->notNull(),
'type' => $this->string()->notNull(),
'created_at' => $this->integer()->unsigned()->notNull(),
```

generalSchema Off:
```
'file_id' => $this->integer(10)->unsigned()->notNull()->append('AUTO_INCREMENT PRIMARY KEY'),
'name' => $this->string(255)->notNull(),
'type' => $this->string(128)->notNull(),
'created_at' => $this->integer(10)->unsigned()->notNull(),
```
any chance to have "On" variant with column sizes?

**Comment by bizley** [comment]
Yes, definitely. This should include column size when it's different than default for general schema.

**Comment by bizley** [comment]
Added in [3.6.0](https://github.com/bizley/yii2-migration/releases/tag/3.6.0) / [2.9.0](https://github.com/bizley/yii2-migration/releases/tag/2.9.0).
