### ISSUE TITLE
Missing 'after' in migration/create (column order not respected)

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-migration#59]
Hi,
`migration/update` ignores column order in generated code - missing `after()` method.

```
$this->addColumn('{{%address}}', 'post', $this->string());
$this->addColumn('{{%address}}', 'commune', $this->string());
```

**Comment by bizley** [comment]
Added in [3.6.0](https://github.com/bizley/yii2-migration/releases/tag/3.6.0) / [2.9.0](https://github.com/bizley/yii2-migration/releases/tag/2.9.0).
