### ISSUE TITLE
ON UPDATE CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by TheElk** [bizley/yii2-migration#6]
" created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP"

Generated migration:
"'created_at' => $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP'),
'updated_at' => $this->timestamp(),"

There are no defaultExpression for second field.
This is bug or expression "ON UPDATE CURRENT_TIMESTAMP" is not universal, and its appliable only to mysql DBs?

Thank you.

**Comment by TheElk** [comment]
This way it works:
"'updated_at' => $this->timestamp()->append('ON UPDATE CURRENT_TIMESTAMP'),"

**Comment by bizley** [comment]
As far as I know it's only supported in MySQL (MariaDB) and Oracle, . MSSQL, PostgreSQL and SQLite are using triggers for the same thing. I have no idea about CUBRID.

Using `append()` for this is the way to go.
