### ISSUE TITLE
Bug in beforeAction

### ISSUE THREAD

**Issue by aiwbend** [bizley/yii2-migration#64]
Expects parameter 1 to be string, array given

https://github.com/bizley/yii2-migration/blob/49ab8cd79636ce2bfa4d07be0da6452d5e86b81d/src/controllers/MigrationController.php#L305

**Comment by bizley** [comment]
What is your version of yii2-migration? This should be already fixed in 3.5.0

**Comment by bizley** [comment]
Could you paste here the configuration you are using? Or full command if there is no special config.

**Comment by aiwbend** [comment]
`console/yii migration/create migration --migrationNamespace="modules\\logging\\repository\\migrations"`

**Comment by aiwbend** [comment]
Look at the latest version of the code, the reason is clearly visible there.)

**Comment by aiwbend** [comment]
Thanks you. Nice library, use it in gii)
