### ISSUE TITLE
MIssing new lines in create_foreign_keys file

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-migration#69]
Hi, a tiny bug?

Version: 3.6.2

After `migration/create` from few tables with foreign keys I got file `m191028_115306_07_create_foreign_keys.php` without new line between `addForeignKey()` call.

Is:
```
$this->addForeignKey('event_ibfk_3', '{{%event}}', 'created_by', '{{%user}}', 'user_id', 'SET NULL', 'CASCADE');        $this->addForeignKey('event_ibfk_4', '{{%event}}', 'updated_by', '{{%user}}', 'user_id', 'SET NULL', 'CASCADE');
```
Should be:
```
$this->addForeignKey('event_ibfk_3', '{{%event}}', 'created_by', '{{%user}}', 'user_id', 'SET NULL', 'CASCADE');
$this->addForeignKey('event_ibfk_4', '{{%event}}', 'updated_by', '{{%user}}', 'user_id', 'SET NULL', 'CASCADE');
```

**Comment by bizley** [comment]
Fixed in [3.6.3](https://github.com/bizley/yii2-migration/releases/tag/3.6.3) / [2.9.3](https://github.com/bizley/yii2-migration/releases/tag/2.9.3). Thank you for reporting.
