### ISSUE TITLE
Error when using namespace

### ISSUE THREAD

**Issue by vuongminh** [bizley/yii2-migration#7]
```php
yii migrate/create-all -h -n="frontend\\migrations"
```

after run command, i change table and update

```php
yii migrate/update-all -h -n="frontend\\migrations"
```

Exception throw:

```
Yii 2 Migration Generator Tool v2.1.2

 > Are you sure you want to potentially generate 16 migrations? [y]es / [n]o [n] y
 > Generating update migration for table 'asset_bundle' ...Exception 'Error' with message 'Class 'CreateUserTable' not found'

in \vendor\bizley\migration\src\Updater.php:187
```

**Comment by vuongminh** [comment]
More information: currently when add `version` in `migration` table it use short name of class (not full namespace)

**Comment by bizley** [comment]
I think this is expected behavior now but maybe some workaround can be done.

Could you set `migrationNamespaces` (--migrationNamespaces, -N) with namespaced version of folder name with the classic migrations? Depending on where you keep them it's i.e. `console\migrations` or similar.

**Comment by vuongminh** [comment]
I had add `migrationNamespaces` in config file

My app config:

```php
    'migrate' => [
            'class' => 'bizley\migration\controllers\MigrationController',
            'migrationTable' => 'm2',
            'migrationNamespaces' => [
                'common\migrations',
                'frontend\migrations'
            ]
        ],
```

**Comment by vuongminh** [comment]
It doesn't work :( missing namespace in `version` problem maybe when generate migration is not prepend namespace? [MigrationController L258](https://github.com/bizley/yii2-migration/blob/master/src/controllers/MigrationController.php#L258)

**Comment by bizley** [comment]
There is bug when extracting data from classic migrations mixed with namespaced. Generally you shoud not mix both but I can add process for proper handling.

One thing bothers me here. Could you paste here the content of your `migration` table?

**Comment by vuongminh** [comment]
Of course! 

![untitled](https://cloud.githubusercontent.com/assets/13974585/26027130/570717fa-3832-11e7-910c-b77aca36ac34.png)

**Comment by bizley** [comment]
Please try the [new version](https://github.com/bizley/yii2-migration/releases/tag/2.2.0) of this extension and let me know if everything is OK.

Unfortunately all the "create" namespaced migrations in your db must be removed and regenerated (or renamed to fit Yii 2 schema `'m' . gmdate('ymd_His') . '_the_rest_of_the_name'`, inside class and `migration` db table).

**Comment by vuongminh** [comment]
It play well now! Thank you for help 🥇 . 

I have a question why we don't skip a `migration table` in list currently it create a migration for `migration table` and we usually remove it before use.

**Comment by bizley** [comment]
Great!

As for the `migration` table - it will be ignored in 2.2.1.
