### ISSUE TITLE
[enh] implement use of * for multiple tables

### ISSUE THREAD

**Issue by sdlins** [bizley/yii2-migration#77]
Hi,

This is just a suggestion of enhancement.

It would be really nice to be able to use something like: `php yii migration/create table_preffix*` to create/update all tables having a name starting with `table_preffix`.

In my use case, we have so many databases and so many preffixes for tables inside each one. Right now, when I need to generate some special group of tables, I have to specify each table name to achieve that.

By the way, thanks for this tool.

**Comment by bizley** [comment]
Really nice idea, thanks! 😄 
I will add it in v4 which is coming soon.

**Comment by bizley** [comment]
Hey, [version 4 RC](https://github.com/bizley/yii2-migration/releases/tag/4.0.0-RC1) is here!

If you could test it and let me know I would really appreciate it.

**Comment by bizley** [comment]
[4.0.0](https://github.com/bizley/yii2-migration/releases/tag/4.0.0) has been released.

**Comment by sdlins** [comment]
Hi @bizley! You didn't mention me so I just saw this now, sorry. ASAP I will update and test and let you know!

Thank you for this great tool!!

**Comment by bizley** [comment]
No problem, cheers.
