### ISSUE TITLE
Doesn't create Indexes

### ISSUE THREAD

**Issue by odannyc** [bizley/yii2-migration#8]
The migrations don't contain Indexes even though they're in my database.
Looks like the code in: 
```https://github.com/bizley/yii2-migration/blob/master/src/views/create_migration.php``` 
only supports uniqueIndexes and not regular Indexes

**Comment by bizley** [comment]
Yes, it's mentioned in the readme. Yii 2 up to 2.0.12 was not storing information about non-unique indexes.

I have not checked the status of this with 2.0.12 version. If it's possible now I will add this for sure.
