### ISSUE TITLE
Maybe can support : insert data

### ISSUE THREAD

**Issue by awebc** [bizley/yii2-migration#80]
like this : migration/create --withData=1
withData:0,1,2
0, no data
1,data and scheme
2,only data

**Comment by bizley** [comment]
I have never used migration that inserts more than few rows of data. With the proposed change it would be possible to create migration that inserts thousands of them, millions. How to deal with that? Is anyone really in true need of such feature? Migrations should not be a database backups.

Please elaborate.

**Comment by awebc** [comment]
Just init table with few rows data

**Comment by bizley** [comment]
Could you provide a use case?

**Comment by awebc** [comment]
`<?php

use yii\db\Migration;

/**
 * Class m200216_023353_insert_init_user
 */
class m200216_023353_insert_init_user extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        // insert admin user: test_admin
        $columns = ['role_id', 'email', 'username', 'password', 'status', 'created_at', 'access_token', 'auth_key'];

        //get data from mysql db , then like this
        $testUsers = [
            [
                1, // Role::ROLE_ADMIN
                'test_admin@test.com',
                'test_admin',
                '$2y$13$XiTEtRWICrPCQV9NfMPnGO5bMBY30w0RT20OwH6SZetjdko2dEXDS',
                1, // User::STATUS_ACTIVE
                gmdate('Y-m-d H:i:s'),
                'xxxxxxxxxx',
                'xxxxxxxx',
            ],
        ];
        
        $this->batchInsert('{{%user}}', $columns, $testUsers);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->truncateTable('user');

        return false;
    }


}
`

**Comment by bizley** [comment]
Yes, this is quite a common case. But not for an automation of generating such migration. Are there any use cases for automation?

**Comment by bizley** [comment]
Closing. We can always reopen it if more info appears. Thank you for the idea though.
