### ISSUE TITLE
teble comment

### ISSUE THREAD

**Issue by Duldris** [bizley/yii2-migration#81]
missing table comment.

the sintax to add manually is:
$this->addCommentOnTable('TABLE_NAME', 'COMMENT');

may you add this automatically?

**Comment by Duldris** [comment]
other way is add comment on table option like this:
$tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB COMMENT="COMMENT HERE"';

**Comment by bizley** [comment]
Unfortunately I can not track this because Yii is not reading the table's comment when fetching its schema.
