### ISSUE TITLE
Nullable not in migration/create

### ISSUE THREAD

**Issue by mbunyan** [bizley/yii2-migration#88]
Puzzled and may be doing something wrong.

With column in db.table has been set to 'not null', running command line migration/create would expect to see line like 
```
password_hash' => $this->string()->notNull(),
```
in the output script, but notNull() does not appear.

This applies whether using --generalSchema=true or --generalSchema=false, which probable does not affect this anyway.

Am I missing a config or trick somewhere?
Mike Bunyan

Working with:
MySQL 5.7
PHP 7.4.5
Yii2 basic 2.0.35
Windows 10

**Comment by bizley** [comment]
I believe this should be detected. Let me verify it and I'll get back to you.

**Comment by bizley** [comment]
There is the specific test covering that case [here](https://github.com/bizley/yii2-migration/blob/master/tests/functional/mysql/GeneratorTest.php#L304).
Could you provide me with the SQL create statement of your case so I can run it on the real data?

**Comment by mbunyan** [comment]
Attached copy of sql dump. The user table is based on Yii2 advanced user table. 

Attached copy of migration output using ```migration/create user```

[m200513_163416_create_table_user.txt](https://github.com/bizley/yii2-migration/files/4623355/m200513_163416_create_table_user.txt)
[user.txt](https://github.com/bizley/yii2-migration/files/4623356/user.txt)

**Comment by bizley** [comment]
Looks like some bug was introduced in 4.0. Thank you for this report, I'll try to patch ASAP

**Comment by bizley** [comment]
Fixed in https://github.com/bizley/yii2-migration/releases/tag/4.0.1

Cheers!
