### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DmitriyLanchakov** [bizley/yii2-migration#9]
**# composer require bizley/migration**

**# php yii migration**
Unknown command: migration
Did you mean "migrate"?

**# php yii**
This is Yii version 2.0.12.
The following commands are available:

- asset                        Allows you to combine and compress your JavaScript and CSS files.
    asset/compress (default)   Combines and compresses the asset files according to the given configuration.
    asset/template             Creates template of configuration file for [[actionCompress]].

- cache                        Allows you to flush cache.
    cache/flush                Flushes given cache components.
    cache/flush-all            Flushes all caches registered in the system.
    cache/flush-schema         Clears DB schema cache for a given connection component.
    cache/index (default)      Lists the caches that can be flushed.

- fixture                      Manages fixture data loading and unloading.
    fixture/load (default)     Loads the specified fixture data.
    fixture/unload             Unloads the specified fixtures.

- gii                          This is the command line version of Gii - a code generator.
    gii/controller             Controller Generator
    gii/crud                   CRUD Generator
    gii/extension              Extension Generator
    gii/form                   Form Generator
    gii/index (default)
    gii/model                  Model Generator
    gii/module                 Module Generator

- hello                        This command echoes the first argument that you have entered.
    hello/index (default)      This command echoes what you have entered as the message.

- help                         Provides help information about console commands.
    help/index (default)       Displays available commands or the detailed information
    help/list                  List all available controllers and actions in machine readable format.
    help/list-action-options   List all available options for the $action in machine readable format.
    help/usage                 Displays usage information for $action

- message                      Extracts messages to be translated from source files.
    message/config             Creates a configuration file for the "extract" command using command line options specified
    message/config-template    Creates a configuration file template for the "extract" command.
    message/extract (default)  Extracts messages to be translated from source code.

- migrate                      Manages application migrations.
    migrate/create             Creates a new migration.
    migrate/down               Downgrades the application by reverting old migrations.
    migrate/history            Displays the migration history.
    migrate/mark               Modifies the migration history to the specified version.
    migrate/new                Displays the un-applied new migrations.
    migrate/redo               Redoes the last few migrations.
    migrate/to                 Upgrades or downgrades till the specified version.
    migrate/up (default)       Upgrades the application by applying new migrations.

- serve                        Runs PHP built-in web server
    serve/index (default)      Runs PHP built-in web server

To see the help of each command, enter:

  yii help <command-name>

**Comment by bizley** [comment]
Have you added

    'controllerMap' => [
        'migration' => [
            'class' => 'bizley\migration\controllers\MigrationController',
        ],
    ],

to your console configuration file?

**Comment by DmitriyLanchakov** [comment]
Yes, that's work.

    'controllerMap' => [
        'migration' => [
            'class' => 'bizley\migration\controllers\MigrationController',
        ],
        'migrate' => [
            'class' => yii\console\controllers\MigrateController::class,
            'templateFile' => '@jamband/schemadump/template.php',
        ],
        'schemadump' => [
            'class' => jamband\schemadump\SchemaDumpController::class,
            'db' => [
                'class' => yii\db\Connection::class,
                'dsn' => 'pgsql:host=localhost;dbname=geos',
                'username' => 'geos',
                'password' => 'geos',
                'charset' => 'utf8',
                'schemaMap' => [
                    'pgsql'=> [
                        'class'=>'yii\db\pgsql\Schema',
                        'defaultSchema' => 'public',
                    ]
                ],
            ],
        ],
    ],

**Comment by bizley** [comment]
So it's working or not?

**Comment by DmitriyLanchakov** [comment]
Yes It's working now.

**Comment by bizley** [comment]
Good. Please follow the instructions given in the README file next time.
