### ISSUE TITLE
CHAR notNull empty defaultValue

### ISSUE THREAD

**Issue by tsvetiligo** [bizley/yii2-migration#92]
$this->char(255)->notNull()->defaultValue('') generates on every update.
$this->char(255)->defaultValue('') works fine.

**Comment by bizley** [comment]
What exactly is the problem here? And which version of package?

**Comment by tsvetiligo** [comment]
version 3.6.5
Migration on every update generates update migration file for `$this->char(255)->notNull()->defaultValue('')` but not for `$this->char(255)->defaultValue('')`.

**Comment by bizley** [comment]
So the column can be `null`? What is the SQL schema of the table?
Also could you check if it's ok in version 4.0.1?

**Comment by tsvetiligo** [comment]
Problem with CHAR NOT NULL
Version 4.0.1 throws error for me - _"Column data must be provided as an instance of yii\db\ColumnSchemaBuilder"_

**Comment by bizley** [comment]
Yes, I cannot properly detect changes for update if column in migration is provided as pure SQL.
Anyway, I still don't understand your problem. Column is set as `NOT NULL` and you don't want the migration to be generated with `->notNull()`?

**Comment by tsvetiligo** [comment]
No.
1 step - create column as _$this->char(255)->notNull()->defaultValue('')_
2 step - run migration/update-all
result - new update migration with alterColumn _$this->char(255)->notNull()->defaultValue('')_

**Comment by bizley** [comment]
Cannot reproduce. v3.6.5 MySQL 5.7.29

Migration:
```
<?php

use yii\db\Migration;

class m200513_183509_create_table_test extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%test}}',
            [
                'char' => $this->char(255)->notNull()->defaultValue(''),
            ],
            $tableOptions
        );
    }

    public function down()
    {
        $this->dropTable('{{%test}}');
    }
}
```

Run `migration/update-all`:
```
Yii 2 Migration Generator Tool v3.6.5

 > Are you sure you want to potentially generate 1 migrations? (yes|no) [no]:yes
 > Generating update migration for table 'test' ...UPDATE NOT REQUIRED.

 No files generated.
```

**Comment by marmartintsang** [comment]
> Problem with CHAR(255) NOT NULL
> Version 4.0.1 throws error for me - _"Column data must be provided as an instance of yii\db\ColumnSchemaBuilder"_

I am facing this issue too

**Comment by bizley** [comment]
Try experimental mode (`-ex=1`, since 4.1.0) to recognize raw SQL in column definition.
