### ISSUE TITLE
Wrong table collation

### ISSUE THREAD

**Issue by honsa** [bizley/yii2-migration#94]
Thank you for this nice generator.

Just one problem at the moment, the generator uses the collation `utf8mb4_unicode_ci` for every table. 

This should be more dynamically cause each table can have an other collation.

**Comment by bizley** [comment]
If I remember correctly Yii is not checking the actual collation of the table so I'm not doing it either. You can always change the collation for the migration file that is generated.

**Comment by honsa** [comment]
Ok, thank you for this information.

**Comment by bizley** [comment]
I'm relying on built-in Yii detection methods, otherwise I would have to prepare this for MySQL and all other supported DB engines. If you would like to prepare PR that could cover it I would be more than happy to accept it.

**Comment by honsa** [comment]
I see this is deep in yii2 and may this should be like it is for simplification.

It is possible to extend `db\ColumnSchema.php` but i dont think this is a good idea, i have to read more about yii and database datatypes and the idea behind.

**Comment by honsa** [comment]
My conclusion is, yii reduces the types for maximal database interoperability. 

So if exact definitions are needed you have to use plain statements.
