### ISSUE TITLE
Longtext becomes text

### ISSUE THREAD

**Issue by honsa** [bizley/yii2-migration#95]
Another little issue which can cause problems:

"longtext" is converted to "text"

**Comment by bizley** [comment]
Can I get more info on that? Which version of package, what database engine, what excatky are you trying to do?

**Comment by honsa** [comment]
Sure mysql 100206, i create a migration of the table "test" which should create an insert statement with the correct datatype

`CREATE TABLE `test`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `longtext` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Get',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3305 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;`

And `yii migration/create test` creates different collation and datatype
`
        $this->createTable(
            '{{%test}}',
            [
                'id' => $this->primaryKey(),
                'longtext' => $this->text()->comment('Get'),
            ],
            $tableOptions
`

**Comment by bizley** [comment]
I'm afraid I cannot do much about this. Yii does not support this type with column schema builder (only maps it from DB to code as `->text()`). You can build your column manually using plain SQL in the migration but this package will not be able to detect it properly during the update.
